name       : libxvmc
version    : 1.0.10
release    : 8
source     :
    - https://www.x.org/releases/individual/lib/libXvMC-1.0.10.tar.gz : d8306f71c798d10409bb181b747c2644e1d60c05773c742c12304ab5aa5c8436
license    :
    - MIT
summary    : X11 Video extension library - MotionCompensation
component  : xorg.library
description: |
    libXvMC provides an X Window System client interface to the
    XVideo-MotionCompensation extension to the X protocol.
builddeps  :
    - pkgconfig(videoproto)
    - pkgconfig32(xext)
    - pkgconfig32(xv)
    - pkgconfig32(x11)
optimize   : speed
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
