name       : libxvmc
version    : 1.0.10
release    : 7
source     :
    - https://www.x.org/releases/individual/lib/libXvMC-1.0.10.tar.gz : d8306f71c798d10409bb181b747c2644e1d60c05773c742c12304ab5aa5c8436
license    :
    - MIT
summary    : X11 Video extension library - MotionCompensation
component  : xorg.library
builddeps  :
    - pkgconfig(xv)
    - pkgconfig32(xv)
    - pkgconfig(videoproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
optimize   : speed
emul32     : yes
description: |
    libXvMC provides an X Window System client interface to the XVideo-MotionCompensation extension to the X protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
