name       : libxvmc
version    : 1.0.11
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libXvMC-1.0.11.tar.gz : 0b931d216b23b95df87cc65f7bb7acef4120d9263adb0a4d90856ba1f7a390da
license    : MIT
component  : xorg.library
summary    : X11 Video extension library - MotionCompensation
description: |
    libXvMC provides an X Window System client interface to the XVideo-MotionCompensation extension to the X protocol.
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig32(xext)
    - pkgconfig32(xv)
    - pkgconfig32(x11)
    - pkgconfig(xproto)
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
