name        : libxvmc
version     : 1.0.9
release     : 6
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.9.tar.gz : 090f087fe65b30b3edfb996c79ff6cf299e473fb25e955fff1c4e9cb624da2c2
license     :
    - MIT
summary     : X11 Video extension library - MotionCompensation
component   : xorg.library
builddeps   :
    - pkgconfig(xv)
    - pkgconfig32(xv)
    - pkgconfig(videoproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
optimize    : speed
emul32      : yes
description : |
    libXvMC provides an X Window System client interface to the XVideo-MotionCompensation extension to the X protocol.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
